// Generated by https://quicktype.io

// export interface ProductResp {
// 	ProductTypes?: ProductType[]
// }

export interface ProductType {
	id: number
	title: string
	price: number
	description: string
	category: string
	image: string
	rating: Rating
}

// export enum Category {
// 	Electronics = 'electronics',
// 	Jewelery = 'jewelery',
// 	MenSClothing = "men's clothing",
// 	WomenSClothing = "women's clothing",
// }

export interface Rating {
	rate: number
	count: number
}
